# Generated by Django 5.0.6 on 2024-06-23 22:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_posts", "0003_comment_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="post_image/"),
        ),
    ]
