# Generated by Django 5.0.6 on 2024-06-24 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_posts", "0005_post_contact_post_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="contact",
            field=models.TextField(),
        ),
    ]
